### ISSUE TITLE
Error: Cannot find module 'moment-interval'

### ISSUE THREAD

**Issue by NinoScript** [lufzle/moment-interval#3]
Requiring moment-interval fails:

``` bash
$ npm install moment-interval
npm http GET https://registry.npmjs.org/moment-interval
npm http 304 https://registry.npmjs.org/moment-interval
npm http GET https://registry.npmjs.org/moment/2.0.0
npm http 304 https://registry.npmjs.org/moment/2.0.0
moment-interval@0.2.0 node_modules/moment-interval
└── moment@2.0.0
$ node
> require('moment-interval')
Error: Cannot find module 'moment-interval'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at repl:1:2
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
```

Normal moment works though

``` bash
$ npm install moment
npm http GET https://registry.npmjs.org/moment
nonpm http 304 https://registry.npmjs.org/moment
demoment@2.4.0 node_modules/moment
$ node
> require('moment')
{ [Function] […]
```

---

I'd love to be able to fix it, but I'm just starting to learn node, I still don't know how the packages work, and I'm not really sure what Grunt is… but if it helps in any way, I read somewhere about a similar error having to do with case sensitivity.

**Comment by cdeszaq** [comment]
:+1:

**Comment by grahamscott** [comment]
I fixed this up here: https://github.com/luisfarzati/moment-interval/pull/5

**Comment by lufzle** [comment]
Thanks @grahamscott! :)
